name: misty_breez
description: "Flutter app showcasing Breez SDK - Nodeless (Liquid Implementation)."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

workspace:
  # Feature Packages
  - packages/breez_preferences
  - packages/sdk_connectivity_cubit
  - packages/device_client
  - packages/keychain
  - packages/lightning_links
  - packages/notifications_client/firebase_notifications_client
  # Utility Packages
  - packages/breez_logger
  - packages/breez_sdk_liquid
  - packages/credentials_manager
  - packages/service_injector

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Feature Packages
  breez_preferences:
    path: packages/breez_preferences
  sdk_connectivity_cubit:
    path: packages/sdk_connectivity_cubit
  device_client:
    path: packages/device_client
  keychain:
    path: packages/keychain
  lightning_links:
    path: packages/lightning_links
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  # Utility Packages
  breez_logger:
    path: packages/breez_logger
  breez_sdk_liquid:
    path: packages/breez_sdk_liquid
  credentials_manager:
    path: packages/credentials_manager
  service_injector:
    path: packages/service_injector

  another_flushbar: ^1.12.30
  archive: ^4.0.4
  auto_size_text: ^3.0.0
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
  flutter_rust_bridge: 2.9.0
  breez_translations:
    git:
      url: https://github.com/breez/Breez-Translations
      ref: a116bd9fa41695f8d0ba22347df679144fd1c5dc
  csv: ^6.0.0
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.3.3
  drag_and_drop_lists:
    git:
      url: https://github.com/breez/DragAndDropLists
      ref: 38cc3155a6161730b4ec476d781873afb7ec4846
  duration: ^4.0.3
  dotted_box: ^0.0.3
  dotted_decoration: ^2.0.0
  email_validator: ^3.0.0
  extended_image: ^10.0.0
  ffi: ^2.1.4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  flutter_fgbg: ^0.7.1
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: 4a494322762af9f30820f3c63aba784d46b86b69
  hex: ^0.2.0
  http: ^1.3.0
  hydrated_bloc: ^10.0.0
  image: ^4.5.3
  # Doesn't support: Linux Mac Windows
  image_cropper: ^9.0.0
  # Doesn't support: Linux Mac Windows
  image_picker: ^1.1.2
  ini: ^2.1.0
  intl: <0.20.0 # timeago ^3.7.0 requires intl >=0.18.0 <0.20.0.
  # Doesn't support: Linux Mac
  local_auth: ^2.3.0
  local_auth_android: ^1.0.48
  local_auth_darwin: ^1.4.3
  logging: ^1.3.0
  lottie: ^3.3.1
  mockito: ^5.4.5
  # Doesn't support: Linux Windows
  mobile_scanner: ^6.0.7
  nested: any
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  shared_preference_app_group: ^1.1.1 # iOS Notification Service extension requirement to access shared preferences
  shimmer: ^3.0.0
  synchronized: ^3.3.1
  theme_provider: ^0.6.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  test: ^1.25.15
  test_api: ^0.7.4

dependency_overrides:
  # Comment-out to work with liquid-sdk from git repository
  breez_liquid:
    path: ../breez-sdk-liquid/packages/dart
  flutter_breez_liquid:
    path: ../breez-sdk-liquid/packages/flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - pubspec.lock
    - assets/images/
    - assets/icons/
    - assets/icons/animals/
    - assets/icons/vendors/
    - assets/animations/
    - assets/animations/welcome/
    - assets/animations/lottie/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
