name: service_injector
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  # Feature Packages
  breez_preferences:
      path: ../breez_preferences
  device_client:
    path: ../device_client
  firebase_notifications_client:
    path: ../notifications_client/firebase_notifications_client
  keychain:
    path: ../keychain
  lightning_links:
    path: ../lightning_links
  # Utility Packages
  breez_logger:
    path: ../breez_logger
  breez_sdk_liquid:
    path: ../breez_sdk_liquid
  credentials_manager:
    path: ../credentials_manager

  logging: ^1.3.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
