name: breez_logger
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  breez_sdk_liquid:
    path: ../breez_sdk_liquid
  breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-dart
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
  archive: ^4.0.2
  device_info_plus: ^11.2.0
  share_plus: ^10.1.3
  logging: ^1.3.0
  rxdart: ^0.28.0

dependency_overrides:
  # Comment-out to work with breez-sdk-liquid from git repository
  breez_liquid:
    path: ../../../breez-sdk-liquid/packages/dart
  flutter_breez_liquid:
    path: ../../../breez-sdk-liquid/packages/flutter