name: breez_logger
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  breez_sdk_liquid:
    path: ../breez_sdk_liquid
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
  archive: ^4.0.5
  device_info_plus: ^11.3.3
  share_plus: ^10.1.4
  logging: ^1.3.0
  rxdart: ^0.28.0
