name: breez_logger
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  breez_sdk_liquid:
    path: ../breez_sdk_liquid
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
  archive: ^4.0.7
  device_info_plus: ^12.1.0
  share_plus: ^12.0.0
  logging: ^1.3.0
  rxdart: ^0.28.0
