name: firebase_notifications_client
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  firebase_messaging: ^15.2.4
  logging: ^1.3.0
  rxdart: ^0.28.0